name: TEST_SSH

on: workflow_dispatch

jobs:
  ssh_job:
    runs-on: ubuntu-latest
      
    steps:
     - run: |
        ls
        cd ..
        tar -cvf "${{ github.event.repository.name }}.tar" "./${{ github.event.repository.name }}/"
        ls
      
     - uses: actions/checkout@master
     - name: Copy repository archive
       uses: dj-256/github-deploy@v1
       with:
        local: "../${{ github.event.repository.name }}.tar"
        remote: "/Users/Administrator/test_123"
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
