name: TEST_SSH

on: workflow_dispatch

jobs:
  ssh_job:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@master
     - run: |
        ls
     - name: local remote scp
       uses: cross-the-world/scp-pipeline@master
       with:
        host: ${{ secrets.DC_HOST }}
        user: ${{ secrets.DC_USER }}
        pass: ${{ secrets.DC_PASS }}
        local: "./README.md"
        remote: "/test456"
