name: TEST_SSH

on: workflow_dispatch

jobs:
  ssh_deploy:
    runs-on: ubuntu-latest
    
    env:
      REPO_NAME_2: ${{ github.event.repository.name }}
    
    steps:
     - name: Use Checkout Action
       uses: actions/checkout@master
     - name: Repo Name to Lower Case
       run: |
         REPO_NAME=$(echo 'console.log("${{ github.event.repository.name }}".toLowerCase())' | node -)
         echo $REPO_NAME
       
     - name: downcase REPO
       run: |
         echo "REPO=${{ github.event.repository.name }}" >>${GITHUB_ENV}
     - name: use REPO
       run: |
         echo "The value of REPO is: ${REPO} || ${{ env.REPO }}"
     
     - name: copy files via key
       uses: appleboy/scp-action@master
       with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "*"
        target: "~/projects/${{ env.REPO }}/"
