name: TEST_SSH

on: workflow_dispatch

jobs:
  ssh_job:
    runs-on: ubuntu-latest
      
    steps:
     - name: Use Checkout Action
       uses: actions/checkout@master
     
     - name: Zip repository files
       run: |
        zip -r ${{ github.event.repository.name }}.zip .
        
     - name: Copy repository archive
       uses: dj-256/github-deploy@v1
       with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        local: "./${{ github.event.repository.name }}.zip"
        remote: "/Users/Administrator/"
        
     - name: Unzip files
       uses: fifsky/ssh-action@master
       with:
         host: ${{ secrets.REMOTE_HOST }}
         user: ${{ secrets.REMOTE_USER }}
         pass: ${{ secrets.REMOTE_PASSWORD}}
         command: |
          cd C:/Users/Administrator/
          echo "%cd%"
          mkdir ${{ github.event.repository.name }}
          powershell -command " Expand-Archive -LiteralPath '${{ github.event.repository.name }}.zip' -DestinationPath '${{ github.event.repository.name }}' -Force "
          del /F "${{ github.event.repository.name }}.zip"
