name: TEST_SSH

on: workflow_dispatch

jobs:
  ssh_deploy:
    runs-on: ubuntu-latest
    
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    
    steps:
     - name: Use Checkout Action
       uses: actions/checkout@master
     
     - name: copy file via ssh password
       uses: appleboy/scp-action@master
       with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "*"
        target: "~/projects/${{ env.REPO_NAME }}"
