name: TEST_SSH

on: workflow_dispatch

jobs:
  ssh_job:
    runs-on: ubuntu-latest
      
    steps:
     - name: Use Checkout Action
       uses: actions/checkout@master
     
     - name: Zip repository files
       run: |
        sudo apt-get install zip -y
        ls
        zip -r ${{ github.event.repository.name }}.zip .
        ls
        
     - name: Copy repository archive
       uses: dj-256/github-deploy@v1
       with:
        local: "./${{ github.event.repository.name }}.zip"
        remote: "/Users/Administrator/"
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        
     - name: ls -a via ssh
       uses: fifsky/ssh-action@master
       with:
         command: |
          cd C:/Users/Administrator/
          echo "%cd%"
          mkdir ${{ github.event.repository.name }}
          unzip ${{ github.event.repository.name }}.zip -d ${{ github.event.repository.name }}
         host: ${{ secrets.REMOTE_HOST }}
         user: ${{ secrets.REMOTE_USER }}
         pass: ${{ secrets.REMOTE_PASSWORD}}
