name: TEST_SSH

on: workflow_dispatch

jobs:
  ssh_job:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@master
     - run: |
        ls
     - name: executing remote ssh commands using password
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.REMOTE_HOST }}
         username: ${{ secrets.REMOTE_USER }}
         password: ${{ secrets.REMOTE_PASSWORD }}
         port: ${{ secrets.REMOTE_PORT }}
         script: |
           whoami
           ls -al
     - name: Copy folder content recursively to remote
       uses: garygrossgarten/github-action-scp@release
       with:
          local: README.md
          remote: test
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
