name: TEST_SSH

on: workflow_dispatch

jobs:
  ssh_job:
    runs-on: ubuntu-latest
      
    steps:
     - name: Use Checkout Action
       uses: actions/checkout@master
     
     - name: Zip repository files
       run: |
        sudo apt-get install zip -y
        ls
        zip -r ${{ github.event.repository.name }}.zip .
        ls
        
     - name: Copy repository archive
       uses: dj-256/github-deploy@v1
       with:
        local: "./${{ github.event.repository.name }}.zip"
        remote: "/Users/Administrator/test_123"
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        
     - name: executing remote ssh commands using password
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.REMOTE_HOST }}
         username: ${{ secrets.REMOTE_USER }}
         password: ${{ secrets.REMOTE_PASSWORD }}
         port: ${{ secrets.REMOTE_PORT }}
         script: |
           whoami
           ls -al
