name: TEST_SSH

on: workflow_dispatch

jobs:
  ssh_job:
    runs-on: ubuntu-latest

    steps:
     - name: hostname -I
       run: |
          hostname -I
          
     - name: executing remote ssh commands using password
       uses: appleboy/ssh-action@master
       with:
        host: leaf.cityhost.com.ua
        username: chdfc1916e
        password: city27Host88
        port: 22
        script: whoami
