name: TEST_SSH

on: workflow_dispatch

jobs:
  ssh_job:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@master
     - run: |
        ls
     - uses: Hermanverschooten/scp-deploy@main
       with:
        local: './'                                                  # Local file path - REQUIRED false - DEFAULT ./
        remote: '~/test0987/'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
        host: ${{secrets.REMOTE_HOST}}                                      # Remote server address - REQUIRED true
        port: ${{secrets.REMOTE_PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
        user: ${{secrets.REMOTE_USER}}                                      # Remote server user - REQUIRED true
        password: ${{secrets.REMOTE_PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key" 
        pre_upload: echo "This will be executed before the upload!"  # Command to run via ssh before scp upload - REQUIRED false
        post_upload: echo "This will be executed after the upload!"  # Command to run via ssh after scp upload - REQUIRED false
        ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
        scp_options: -v                                              # Flags to use during scp - REQUIRED false - DEFAULT ''
