name: TEST_SSH

on: workflow_dispatch

jobs:
  ssh_job:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      
    steps:
     - run: |
        ls
        echo "REPO_NAME = $REPO_NAME"
        cd ..
        tar -cvf "$REPO_NAME.zip" "./$REPO_NAME/"
        ls
      
     - uses: actions/checkout@master
     - name: Copy repository archive
       uses: dj-256/github-deploy@v1
       with:
        local: "../${{ REPO_NAME }}.tar"
        remote: "/Users/Administrator/test_123"
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
