name: TEST_SSH

on: workflow_dispatch

jobs:
  ssh_job:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@master
     - run: |
        ls
     - name: Copy single file
       uses: dj-256/github-deploy@v1
       with:
        local: "README.md"
        remote: "/"
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
